<a href="https://colab.research.google.com/github/boywaiter/nlp_notes/blob/master/nlp_notes02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Chapter 2 Linear Text Claasification

**text classification**: given a text document, assign it a discrete label $y\in\mathcal{Y}$, where $\mathcal Y$ is the set of possible labels.

2.1 The bag of words


In [0]:
import torch

In [0]:
K=3
V=5
x=torch.randint(10,(V,1))
x=torch.cat((x,torch.ones(1,1,dtype=torch.long)),0)
weights=torch.ones(K*(V+1))

In [0]:
def feature_function(x,y):
  return {(y-1)*(V+1)+i:x[i] for i in range(0,V+1)}

In [0]:
print(feature_function(x,2))

{6: tensor([7]), 7: tensor([5]), 8: tensor([8]), 9: tensor([7]), 10: tensor([1]), 11: tensor([1])}


In [0]:
def compute_score(x,y,weights):
  total=0
  for feature, count in feature_function(x,y).items():
    total+=weights[feature] * count
  return total

In [0]:
print(x)
print(weights)
total=compute_score(x,2,weights)
print(total)

tensor([[7],
        [5],
        [8],
        [7],
        [1],
        [1]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([29.])


2.2 Naive Bayes

2.3 Discriminative learning

In [0]:
Word_count_max=10
N=10
V=5
K=2
X=torch.randint(low=1,high=Word_count_max,size=(N,V))
X=torch.cat((X,torch.zeros(N,1,dtype=torch.long)),1)
y=torch.randint(0,K,size=(N,1))

In [0]:
import numpy as np
def feature_function_binary(x,y):
  dict1={y*(V+1)+i:x[i].item() for i in range(0,V+1)}  
  dict2={(1-y)*(V+1)+i:0 for i in range(0,V+1)}
  dict3={}
  dict3.update(dict1)
  dict3.update(dict2)
  return dict3
def update_theta(theta,D1,D2):
  for feature, count in D1.items():
    theta[feature]+=count-D2[feature]
  return theta
def compute_score_binary(x,y,weights):
  total=0
  for feature, count in feature_function_binary(x,y).items():
    #print("feature=",feature)
    #print("count=",count)
    total+=weights[feature] * count
  return total
def perceptron(X,y):
  t=0
  theta=torch.zeros(K*(V+1),dtype=torch.float)
  #print("theta=",theta)
  times=10
  while(t<times):
    i= np.random.randint(0,N,1).item()
    x=X[i]    
    #print("x=",x)
    hat_y=0 if compute_score_binary(x,0,theta).item()>=compute_score_binary(x,1,theta).item() else 1
    print("hat_y=",hat_y,"y[i]=",y[i].item())
    if(hat_y!=y[i].item()):
      theta=update_theta(theta,feature_function_binary(x,y[i].item()),
                         feature_function_binary(x,hat_y))
    t+=1
  return theta

In [0]:
theta=perceptron(X,y)
print(theta)

hat_y= 0 y[i]= 1
hat_y= 1 y[i]= 1
hat_y= 1 y[i]= 1
hat_y= 1 y[i]= 1
hat_y= 1 y[i]= 1
hat_y= 1 y[i]= 0
hat_y= 0 y[i]= 0
hat_y= 0 y[i]= 0
hat_y= 1 y[i]= 0
hat_y= 0 y[i]= 0
tensor([ 7.,  1.,  7.,  7.,  3.,  0., -7., -1., -7., -7., -3.,  0.])
